config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  devise_for :users
  root to: 'movies#index'

  resources :movies do
    resources :reviews
  end
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  has_many :articles
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    redirect_to root_path, notice: "You don't have permission to do that!" unless current_user.id == @article.user_id
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :image)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user_id = current_user.id
    if @movie.save
      redirect_to @movie
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
    redirect_to root_path, notice: "You don't have permission to do that!" unless current_user.id == @movie.user_id
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to root_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :overview, :year, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.create(review_params)
    @review.user = current_user
    @review.save
    redirect_to movie_path(@movie)
  end

  private
    def review_params
      params.require(:review).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="mt-2">
    <%= form.label :title, class: 'text-2xl text-blue-900' %><br>
    <%= form.text_field :title, class: 'w-full bg-gray-100 outline-none rounded' %>
  </div>
  <div class="mt-2">
    <%= form.label :body, class: 'text-2xl text-blue-900' %><br>
    <%= form.text_area :body, class: 'w-full bg-gray-100 outline-none rounded' %>
  </div>

  <div class="flex mt-2 space-x-2">
    <% if article.image.attached? %>
      <div class="w-1/2">
        <%= image_tag article.image %>
      </div>
    <% else %>
      <div class="w-1/2 flex m-auto justify-center">
        Image here
      </div>
    <% end %>
    <div class="w-1/2">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>

  <div class="flex justify-center">
    <% if current_page?(:controller => 'articles', :action => 'new') %>
      <%= form.submit "ADD ARTICLE", class: 'font-bold mt-4 px-4 py-2 text-white bg-blue-900 hover:bg-blue-800' %>
    <% else %>
      <%= form.submit "SAVE", class: 'font-bold mt-4 px-4 py-2 text-white bg-blue-900 hover:bg-blue-800'%>
    <% end %>
  </div>
<% end %>

app/views/articles/index.html.erb
<div class="mx-auto" style="width: 800px;">
  <h1 class="flex mt-8 font-bold text-blue-900 flex-row justify-between">
    <span class="border-b-2 text-3xl border-blue-900">
      Articles
    </span>
    <%= link_to "NEW ARTICLE", new_article_path, class: 'text-white px-4 py-2 bg-blue-900 hover:bg-blue-800' %>
  </h1>
  <div class="grid gap-4 grid-cols-1 mt-8 pb-20 mx-auto">
    <% @articles.each do |article| %>
      <%= link_to article do %>
        <div class="flex flex-row bg-white hover:shadow-lg">
          <div class="w-1/4 h-48 flex">
            <% if article.image.attached? %>
              <%= image_tag article.image, class: 'h-full px-4 py-4' %>
            <% else %>
              <div class="text-center m-auto px-3 py-3 text-blue-600 font-bold">
                * No image yet
              </div>
            <% end %>
          </div>
          <div class="w-3/4 flex flex-col py-4 pr-4">
            <span class="text-blue-900 font-bold text-3xl">
              <%= article.title %>
            </span>
            <div class="text-gray-500 text-lg line-clamp-4">
                <%= article.body %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-auto mt-20" style="width: 400px;">
  <span class="font-bold text-blue-900 border-b-2 text-3xl border-blue-900">
    New Article
  </span>
  <div class="mt-8">
    <%= render "form", article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="mx-auto mt-20 flex flex-col items-end" style="width: 800px;">
  <div class="flex flex-row bg-white w-full">
    <div class="w-1/4 h-48 flex">
      <% if @article.image.attached? %>
        <%= image_tag @article.image, class: 'h-full px-4 py-4' %>
      <% else %>
        <div class="text-center m-auto px-3 py-3 text-blue-600 font-bold">
          * No image yet
        </div>
      <% end %>
    </div>
    <div class="w-3/4 flex flex-col py-4 pr-4 space-y-2">
      <div class="flex flex-row justify-between">
        <div class="text-blue-900 font-bold text-3xl">
          <%= @article.title %>
        </div>
        <%= link_to "EDIT", edit_article_path(@article), class: 'font-semibold px-4 py-2 text-white bg-blue-900 hover:bg-blue-800' %>
      </div>
      <div class="text-gray-500 text-lg">
          <%= @article.body %>
      </div>
      <div class="font-semibold">
        Added by
        <span class="text-blue-700">
          <%= @article.user.email %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.svg' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="font-dosis h-screen bg-blue-100">
    <%= render 'shared/navbar' %>

    <div class="h-full">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie do |form| %>
  <div class="flex flex-row justify-between space-x-2">
    <div class="w-1/2">
      <%= form.label :title, class: 'text-2xl text-blue-900' %><br>
      <%= form.text_field :title, class: 'w-full bg-gray-100 outline-none rounded' %>
      <% @movie.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div class="w-1/2">
      <%= form.label :year, class: 'text-2xl text-blue-900' %><br>
      <%= form.text_field :year, class: 'w-full bg-gray-100 outline-none rounded' %>
      <% @movie.errors.full_messages_for(:year).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="mt-2">
    <%= form.label :overview, class: 'text-2xl text-blue-900' %><br>
    <%= form.text_area :overview, class: 'w-full bg-gray-100 outline-none rounded' %>
    <% @movie.errors.full_messages_for(:overview).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="flex mt-2 space-x-2">
    <% if movie.image.attached? %>
      <div class="w-1/2">
        <%= image_tag movie.image %>
      </div>
    <% else %>
      <div class="w-1/2 flex m-auto justify-center">
        Image here
      </div>
    <% end %>
    <div class="w-1/2">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>

  <div class="flex justify-center">
    <% if current_page?(:controller => 'movies', :action => 'new') %>
      <%= form.submit "ADD MOVIE", class: 'font-bold mt-4 px-4 py-2 text-white bg-blue-900 hover:bg-blue-800' %>
    <% else %>
      <%= form.submit "SAVE", class: 'font-bold mt-4 px-4 py-2 text-white bg-blue-900 hover:bg-blue-800'%>
    <% end %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="mx-auto mt-20" style="width: 400px;">
  <span class="font-bold text-blue-900 border-b-2 text-3xl border-blue-900">
    Edit Movie
  </span>
  <div class="mt-8">
    <%= render "form", movie: @movie %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="mx-auto" style="width: 800px;">
  <h1 class="flex mt-8 font-bold text-blue-900 flex-row justify-between">
    <span class="border-b-2 text-3xl border-blue-900">
      Movies
    </span>
    <%= link_to "NEW MOVIE", new_movie_path, class: 'text-white px-4 py-2 bg-blue-900 hover:bg-blue-800' %>
  </h1>
  <div class="grid gap-4 grid-cols-1 mt-8 pb-20 mx-auto">
    <% @movies.each do |movie| %>
      <%= link_to movie do %>
        <div class="flex flex-row bg-white hover:shadow-lg">
          <div class="w-1/4 h-48 flex">
            <% if movie.image.attached? %>
              <%= image_tag movie.image, class: 'h-full px-4 py-4' %>
            <% else %>
              <div class="text-center m-auto px-3 py-3 text-blue-600 font-bold">
                * No image yet
              </div>
            <% end %>
          </div>
          <div class="w-3/4 flex flex-col py-4 pr-4">
            <div>
              <span class="text-blue-900 font-bold text-3xl">
                <%= movie.title %>
              </span>
              <span class="text-gray-500 text-lg">
                <%= movie.year %>
              </span>
            </div>
            <div class="text-gray-500 text-lg line-clamp-4">
                <%= movie.overview %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="mx-auto mt-20" style="width: 400px;">
  <span class="font-bold text-blue-900 border-b-2 text-3xl border-blue-900">
    New Movie
  </span>
  <div class="mt-8">
    <%= render "form", movie: @movie %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="mx-auto mt-20 flex flex-col items-end" style="width: 800px;">
  <div class="flex flex-row bg-white w-full">
    <div class="w-1/4 h-48 flex">
      <% if @movie.image.attached? %>
        <%= image_tag @movie.image, class: 'h-full px-4 py-4' %>
      <% else %>
        <div class="text-center m-auto px-3 py-3 text-blue-600 font-bold">
          * No image yet
        </div>
      <% end %>
    </div>
    <div class="w-3/4 flex flex-col py-4 pr-4 space-y-2">
      <div class="flex flex-row justify-between">
        <div>
          <span class="text-blue-900 font-bold text-3xl">
            <%= @movie.title %>
          </span>
          <span class="text-gray-500 text-lg">
            <%= @movie.year %>
          </span>
        </div>
        <%= link_to "EDIT", edit_movie_path(@movie), class: 'font-semibold px-4 py-2 text-white bg-blue-900 hover:bg-blue-800' %>
      </div>
      <div class="text-gray-500 text-lg">
          <%= @movie.overview %>
      </div>
      <div class="font-semibold">
        Added by
        <span class="text-blue-700">
          <%= @movie.user.email %>
        </span>
      </div>
    </div>
  </div>
  <div class="mt-4">
    <%= render "reviews/form" %>
  </div>

  <div class="w-3/4 grid grid-cols-1 space-y-2 mt-4">
    <span class="font-bold text-blue-900 border-b-2 text-3xl border-blue-900">Reviews</span>
    <% @movie.reviews.each do |review| %>
      <div class="flex flex-col bg-white px-4 py-4 justify-between">
        <div class="text-lg">
          <%= review.body %>
        </div>
        <div class="flex justify-end font-bold text-blue-900">
          <%= review&.user&.email %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_with model: [ @movie, @movie.reviews.build ] do |form| %>
  <div class="flex flex-row items-center space-x-2 justify-end">
    <div class="mt-2">
      <%= form.text_area :body, class: 'w-96 bg-gray-100 outline-none rounded' %>
    </div>
    <p>
      <%= form.submit "ADD REVIEW", class: 'px-4 py-2 bg-blue-900 text-white hover:bg-blue-800 cursor-pointer font-semibold' %>
    </p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="grid grid-cols-3 px-6 py-2 bg-blue-900">
  <div class="flex items-center">
    <a href="/" class="flex flex-row items-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="white">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
      </svg>
      <span class="text-white ml-2 text-xl font-semibold">Know Eye Deer</span>
    </a>
  </div>

  <div class="flex flex-row justify-self-center items-center space-x-2 text-white font-semibold">
    <%= link_to 'Movies', movies_path, class: 'px-4 py-2 hover:bg-white hover:text-blue-900' %>
      <%= link_to 'Articles', articles_path, class: 'px-4 py-2 hover:bg-white hover:text-blue-900' %>
  </div>

  <div class="flex flex-row justify-self-end items-center space-x-2 text-white font-semibold">
    <% if user_signed_in? %>
      <span>Hello, <%= current_user.email %></span>
      <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: 'px-4 py-2 hover:bg-white hover:text-blue-900' %>
    <% else %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: 'px-4 py-2 hover:bg-white hover:text-blue-900' %>
      <%= link_to 'LOG IN', new_user_session_path, class: 'px-4 py-2 hover:bg-white hover:text-blue-900' %>
    <% end %>
  </div>
</nav>

app/views/shared/_warning.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>